Moderate Updates

diff --git a/bin/builder b/bin/builder
--- a/bin/builder
+++ b/bin/builder
@@ -2,7 +2,7 @@
 # builder	a small script to build software for Linux distros
 #
 # Created	2017/07/08 by Dave Henderson (support@cliquesoft.org)
-# Updated	2026/03/26 by Dave Henderson (support@cliquesoft.org)
+# Updated	2026/03/31 by Dave Henderson (support@cliquesoft.org)
 #
 # License	2-clause BSD License
 #		https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29
@@ -218,12 +218,13 @@ export FLAG_MAKE=''						# the flags to pass to the 'make' call
 
 # Syntax: stop TYPE [EXIT]
 # Exits gracefully by cleaning up the desired parts of the file system after a failed build
-# TYPE	the type of cleanup to perform: failed, clean (for multi-pass), proper
-# EXIT	if the function should exit this script afterwards: 0=no, 1=yes (default)
+# TYPE		[string] the type of cleanup to perform: failed, clean (for multi-pass), proper, normal
+# EXIT		[number] if the function should exit this script afterwards: 0=no, 1=yes (default)
+#		[ NOTE ] if TYPE != 'failed,clean,proper' this value becomes the exit code
 stop() {
 	[ "$1" = 'failed' ] && echo "ERROR: This step failed to complete, check the log for details."
 
-	[ "$DEP_MAKE_PAK" ] && [ "$SPM_UNLD" ] && [ "$UNLOAD" ] && {
+	[ "$1" = 'quit' ] && [ "$DEP_MAKE_PAK" ] && [ "$SPM_UNLD" ] && [ "$UNLOAD" ] && {
 		echo -e "\nUnloading compile-time dependencies..." | tee -a "$LOG"
 		eval "$SPM_UNLD 2>>\"$LOG\""
 	}
@@ -256,7 +257,40 @@ stop() {
 		done
 		[ -x "${DIR_PROF}/${NAME}/cleanup" ] && "${DIR_PROF}/${NAME}/cleanup" 2>>"$LOG"	# if a cleanup script has been included, execute it as well!
 		( [ ! "$2" ] || [ $2 -eq 1 ] ) && exit 0
+	else							# this is the 'normal' (or any other value)
+		[ ! "$2" ] && exit 0 || exit $2
 	fi
+}
+
+
+
+
+# Syntax: pass ACTION FILE
+# parses the NAME.pass file and assigns value to PASS variable
+# ACTION	[string] method of operation:
+#			 init - checks for multi-pass and assigns a temp value to PASS
+#			 inc  - read the NAME.pass file and increment the PASS value by one
+# FILE		[string] the file to check: config, params
+pass() {
+	[ ! -e "${DIR_TEMP}/${NAME}.pass" ] && {						# if there are no passes -OR- no passes have been made yet (e.g. this is the initial invocation), then...
+		[ "$2" ] && [ -e "${DIR_PROF}/${NAME}/${2}.1" ] && {				#   if a FILE was passed -AND- the initial file exists, then...
+echo 'pass() init'
+			[ "$2" = 'config' ] && TEMP='INIT'					#      indicate we are doing a multi-pass
+			[ "$2" = 'params' ] && TEMP="$PASS"					#      indicate we are doing a multi-pass
+			PASS=1									#      set the variable to an initial value so the params.1 file can be processed
+			return
+		}
+
+echo 'pass() exit'
+return						# if no params.* files exist, nor does a NAME.pass, then this isn't a multi-pass profile so we can exit
+	}
+echo 'pass() process'
+	PASS="$(cat "${DIR_TEMP}/${NAME}.pass")"
+	TEMP=${PASS%|*}										#   store the total passes required
+	PASS=${PASS#*|}										#   store the prior pass value
+	[ "$1" = 'INC' ] && PASS=$(( PASS + 1 ))						#   increase the value by 1 if instructed to
+	[ $PASS -gt $TEMP ] && stop proper							#   if we have just completed the last requred pass, then cleanup and exit
+	[ "$1" = 'INC' ] && echo "$TEMP|$PASS" >"${DIR_TEMP}/${NAME}.pass"			#   if we've made it here, we still have at least one pass to perform, so update the values!
 }
 
 
@@ -392,9 +426,9 @@ package() {
 
 
 	# CREATE EACH PACKAGE
-
+echo "skip pass|$SKIP|$PASS|"
 	[ ! "$SKIP" ] && [ "$PASS" ] && [ $PASS -lt $(cat "${DIR_TEMP}/${NAME}.pass" | sed 's/|.*//') ] && {
-		[ $DEBUG -gt 0 ] && echo "   DEBUG: The -F and -N was passed, but we're not on the last pass."
+		[ $DEBUG -gt 0 ] && echo "   DEBUG: The -F and -N were passed, but we're not on the last pass."
 		return 0									# if '-F' was passed -AND- '-N' was passed -AND- we are on the last pass, then exit this function
 	}
 
@@ -496,15 +530,40 @@ package() {
 # LOAD PROFILE CONFIGURATION
 
 eval "NAME=\${$#}"										# store the current last passed value (which should be the NAME)
-[ ! "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config" ] && . "${DIR_PROF}/${NAME}/config"		# Profile config
-[ "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config.${PASS}" ] && . "${DIR_PROF}/${NAME}/config.${PASS}"						# ditto, but for multi-pass
+echo "@ |$@|"
+if ( ! echo "$@" | grep -q '\-u ' ); then							# if we're not uninstalling a profile, then...
+echo 'uninstall was NOT passed'
+	TEMP=''
+	pass 'init' 'config'										# check if we have a multi-pass profile
+	[ ! "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config" ] && {
+echo 'reading in config file'
+. "${DIR_PROF}/${NAME}/config"		# Profile config
+}
+	[ "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config.${PASS}" ] && {
+echo "reading in config.$PASS file"
+. "${DIR_PROF}/${NAME}/config.${PASS}"						# ditto, but for multi-pass
+}
+	[ "$TEMP" = 'INIT' ] && { TEMP=''; PASS=''; }							# if this was an initial invocation of the multi-pass profile, then reset these variables
+fi
 
-# LOAD SWITCH DEFAULTS
+# LOAD PARAMETER DEFAULTS
 
-[ -e "${DIR_PROF}/${NAME}/params" ] && . "${DIR_PROF}/${NAME}/params"				# Profile parameters (general)
-[ -e "${DIR_PROF}/${NAME}/params.${PASS}" ] && . "${DIR_PROF}/${NAME}/params.${PASS}"		# ditto, but for multi-pass (specific)
+if ( ! echo "$@" | grep -q '\-u ' ); then							# if we're not uninstalling a profile, then...
+echo 'uninstall was NOT passed'
+	[ -e "${DIR_PROF}/${NAME}/params" ] && {
+echo 'reading in params file'
+. "${DIR_PROF}/${NAME}/params"				# Profile parameters (general)			  NOTE: both of these files can be processed in a multi-pass profile
+}
+	TEMP=''
+	pass 'init' 'params'										# check if we have a multi-pass profile
+	[ -e "${DIR_PROF}/${NAME}/params.${PASS}" ] && {
+echo "reading in params.$PASS file"
+. "${DIR_PROF}/${NAME}/params.${PASS}"		# ditto, but for multi-pass (specific)
+}
+	[ "$TEMP" ] && { PASS="$TEMP"; }								# if this was an initial invocation of the multi-pass profile, then restore the params PASS value
+fi
 
-
+echo "TYPE 1 |$TYPE|$PASS|"
 
 
 # PROCESS THE PASSED SWITCHES
@@ -696,7 +755,7 @@ else
 		esac
 	done
 
-
+echo "TYPE 2 |$TYPE|"
 
 
 	# TEST FOR MANDATORY VALUE(S)
@@ -885,7 +944,7 @@ elif [ "$PASS" ]; then
 fi
 
 
-
+echo "TYPE 3 |$TYPE|"
 
 # CHANGE DIRECTORY
 
@@ -921,6 +980,7 @@ if [ "$DOWNLOAD" ]; then
 		echo " [done]" | tee -a "$LOG"
 	fi
 	[ ! "$INSTALL" ] && exit 0								# if we're not also installing the profile, then we need to exit
+echo "TYPE 4 |$TYPE|"
 fi
 
 # NOTE: these have to be separate 'if' statements so ONLY these two can be chained with others!
@@ -961,13 +1021,22 @@ if [ "$INSTALL" ]; then
 	# if we're not also building or compiling, then we need to exit
 	[ ! "$BUILD" ] && exit 0
 
-	# otherwise, load the profile configuraiton
-	[ ! "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config" ] && . "${DIR_PROF}/${NAME}/config"
-	[ "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config.${PASS}" ] && . "${DIR_PROF}/${NAME}/config.${PASS}"
+#echo "CMD 1 |$EXE_CMD|"
+	EXE_CMD="$(echo "$EXE_CMD" | sed 's/ -d//;s/ -i//')"	# retain the current builder call without the -i or -d parameters
+#echo "CMD 2 |$EXE_CMD|"
+	exec $EXE_CMD						# re-launch builder using the adjusted parameters
+								# NOTE: exec will replace this invocation of the script with the above line	https://stackoverflow.com/questions/18351198/what-are-the-uses-of-the-exec-command-in-shell-scripts
+#echo DBUG
+#exit 0
 
-	# and any switch configurations
-	[ ! "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/params" ] && . "${DIR_PROF}/${NAME}/params"
-	[ "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/params.${PASS}" ] && . "${DIR_PROF}/${NAME}/params.${PASS}"
+#	# otherwise, load the profile configuraiton
+#	[ ! "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config" ] && . "${DIR_PROF}/${NAME}/config"
+#	[ "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/config.${PASS}" ] && . "${DIR_PROF}/${NAME}/config.${PASS}"
+#
+#	# and any switch configurations
+#	[ ! "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/params" ] && . "${DIR_PROF}/${NAME}/params"
+#	[ "$PASS" ] && [ -e "${DIR_PROF}/${NAME}/params.${PASS}" ] && . "${DIR_PROF}/${NAME}/params.${PASS}"
+echo "TYPE 5 |$TYPE|"
 fi
 
 # NOTE: these have to be separate 'if' statements so ONLY these two can be chained with others!
@@ -1305,7 +1374,7 @@ elif [ "$UNINSTALL" ]; then
 fi
 
 
-
+echo "TYPE 6 |$TYPE|"
 
 # BEGIN THE BUILD/COMPILE PROCESS
 
@@ -1335,8 +1404,9 @@ fi
 
 # if any directory exists -AND- we are doing a single pass -or- on the first pass of a multi-pass (via cli or params file) and the .pass file doesn't exist (via 'stop failed'), then...
 if ( ls -1 "${DIR_TEMP}/${NAME}" | grep -q . ) || ( ls -1 "${DIR_DUMP}/${NAME}" | grep -q . ) || [ -d "${DIR_DUMP}/${NAME}.bin" ]; then
-	echo -n "It appears a prior (attempted) compile has left files, cleanup? [Y/N] (N): "
+	echo -n "It appears a prior (attempted) compile has left files, cleanup? [Y/N/Q] (N): "
 	read
+	[ "$REPLY" = 'Q' ] || [ "$REPLY" = 'q' ] && stop					# NOTE: the script does NOT stop here if 'yes' was requested
 	[ "$REPLY" = 'Y' ] || [ "$REPLY" = 'y' ] && stop proper 0				# NOTE: the script does NOT stop here if 'yes' was requested
 fi
 
@@ -1345,14 +1415,16 @@ fi
 
 # GET/SET THE 'PASS' AND 'SUDO' VALUES				  NOTE: the DIR_TEMP value will already be (re)set by this point
 
-[ -e "${DIR_TEMP}/${NAME}.pass" ] && {				# if we are on one of the multi-passes, then...    WARNING: this has to be processed in this order -AND- do NOT test for PASS value since it does NOT get passed on subsequent calls!
-	PASS="$(cat "${DIR_TEMP}/${NAME}.pass")"
-	TEMP=${PASS%|*}						#   store the total passes required
-	PASS=${PASS#*|}						#   store the prior pass value
-	PASS=$(( PASS + 1 ))					#   increase the value by 1
-	[ $PASS -gt $TEMP ] && stop proper			#   if we have just completed the last requred pass, then cleanup and exit
-	echo "${TEMP}|${PASS}" >"${DIR_TEMP}/${NAME}.pass"	#   if we've made it here, we still have at least one pass to perform, so update the values!
-}
+# UPDATED 2026/03/31
+#[ -e "${DIR_TEMP}/${NAME}.pass" ] && {				# if we are on one of the multi-passes, then...    WARNING: this has to be processed in this order -AND- do NOT test for PASS value since it does NOT get passed on subsequent calls!
+#	PASS="$(cat "${DIR_TEMP}/${NAME}.pass")"
+#	TEMP=${PASS%|*}						#   store the total passes required
+#	PASS=${PASS#*|}						#   store the prior pass value
+#	PASS=$(( PASS + 1 ))					#   increase the value by 1
+#	[ $PASS -gt $TEMP ] && stop proper			#   if we have just completed the last requred pass, then cleanup and exit
+#	echo "${TEMP}|${PASS}" >"${DIR_TEMP}/${NAME}.pass"	#   if we've made it here, we still have at least one pass to perform, so update the values!
+#}
+[ -e "${DIR_TEMP}/${NAME}.pass" ] && pass 'inc'			# if we are on one of the multi-passes, then...    WARNING: this has to be processed in this order -AND- do NOT test for PASS value since it does NOT get passed on subsequent calls!
 
 [ "$PASS" ] && [ ! -e "${DIR_TEMP}/${NAME}.pass" ] && {		# if we need to perform multi-passes and none are recorded yet, then...
 	echo "${PASS}|1" >"${DIR_TEMP}/${NAME}.pass"		#   stored value in format of: TOTAL|CURRENT
@@ -1821,7 +1893,8 @@ fi
 
 [ "$PASS" ] && {
 	echo -e "\nStarting the next pass..." | tee -a "$LOG"
-
+# passed D P F T lib U alsa
+# LEFT OFF - if any of these are in the 'params' or 'params.*' files, then do NOT include them below!
 	TEMP='"$THIS" -A "$ARCH" -M "$METHOD"'
 	[ "$SOURCE" != '' ] && TEMP="$TEMP -C $SOURCE"
 	[ "$DIRS" ] && TEMP="$TEMP -D"
